server.tomcat.accesslog.directory=C:/temp/oauth-demo/accesslog
server.tomcat.accesslog.prefix=resource-access
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=time:%t host:%h thread:%I sessionid:%S  protocol:%H method:%m path:%U%q status:%s size:%b reqtime_millis:%D

#security.basic.enabled=false

 spring.datasource.url=jdbc:mariadb://localhost:3306/mds_annuaire_client?createDatabaseIfNotExist=true
 #utilisateur de la bdd
 spring.datasource.username=root
 #mot de passe
 spring.datasource.password=utP@j<b.
 #pilote de connexion 
 spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
